### ISSUE TITLE
hooks not being delayed?

### ISSUE THREAD

**Issue by ar4s-eth** [GalloDaSballo/magic-wallet#3]
Forgive me, I'm a Junior dev who's looking forward to building on your wonderful project. 

I noticed that when plugging in a new API endpoint (tokenlist) that I was getting status 429 responses after a little bit. 

It looks like useETHBalance/useERCBalance are not being delayed by useEffect's setTimeout ... I've used some other references for how do this properly in react -[like here](https://stackoverflow.com/questions/53090432/react-hooks-right-way-to-clear-timeouts-and-intervals)- and everything looks like it should be working. 

Unless I'm missing something (I dropped a console log into the hooks to see how often they were being called, and it seems like after every render).... shouldn't these functions only be called every 15 seconds via reload()?

Thank you!

**Comment by GalloDaSballo** [comment]
I remember having a similar issue and I think it's because the user keeps being updated.

I'd recommend you check in the UserContext, and make some edits to avoid it from re-rendering constantly.
I fixed the issue on a similar project, see here: https://github.com/GalloDaSballo/polygon-yield/blob/main/packages/next/context/UserContext.tsx

**Comment by GalloDaSballo** [comment]
To answer more directly, both hooks use user in the dependency list, if the user keeps changing, then they keep getting re-triggered

**Comment by ar4s-eth** [comment]
Thanks for the leads(!), I probably wouldn't have figured that out on my own lol.

**Comment by ar4s-eth** [comment]
Not sure it was the right solution, but I removed "logout"  from persistUser's dependency array.
